name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: | 
                      👋 Hi! Thank you for reporting your first issue. To help us resolve it efficiently, 
                      please consider including: steps to reproduce, your environment (OS, version), and any relevant error messages. 
                      If you have any further information, feel free to add it in the comments!.
        pr-message: | 
                    🎉 Congratulations on your first pull request to this repository! 
                    We're excited to see your contribution. Please ensure your PR follows our contributing guidelines. 
                    We'll review it carefully and provide feedback.
